name: red_zone
description: "“RedZone” - Real-Time Natural Disasters Prevention Alerts and Risk Management Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  lottie: ^3.0.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  webview_flutter: ^4.7.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0

  # Icons
  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.4

  # Google Maps
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  firebase_messaging: ^14.7.19
  shared_preferences: ^2.2.2


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
    - assets/images/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
