name: red_zone
description: "“RedZone” - Real-Time Natural Disasters Prevention Alerts and Risk Management Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.6.6

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
    - assets/images/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/user/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
